
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sanwaliya_devlopment

  
production:
  <<: *default
  database: sanwaliya_production
  username: postgres
  password: postgres
